### ISSUE TITLE
Question about AVX2

### ISSUE THREAD

**Issue by Z-Y00** [Const-me/SimdIntroArticle#1]
Hi, 
thanks for your wonderful blog here 
https://github.com/Const-me/SimdIntroArticle/blob/master/DotProduct/dpps.cpp
I'm thinking that you can use this: 
https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/intrinsics/intrinsics-for-intel-advanced-vector-extensions-2/intrinsics-for-fused-multiply-add-operations/mm-fmadd-pd-mm256-fmadd-pd.html

It will do the add and multi at same time!

**Comment by Z-Y00** [comment]
I think this can be faster
https://github.com/horovod/horovod/blob/16297493ac5fe8b0dbb303b9cbf66d8178b727e2/horovod/common/ops/adasum/adasum.h#L440

Oh, sorry about that, I found in your target machine, this AVX2 is not enabled

**Comment by Const-me** [comment]
@Z-Y00 Indeed, that version was specifically testing `dpps`.
Here's one that uses FMA: https://github.com/Const-me/SimdIntroArticle/blob/master/DotProduct/vertical.cpp#L26-L44
